// scripts/generate-club-sitemap.js
//
// Build-time sitemap generator.
//
// Writes a SINGLE public/sitemap.xml. A sitemap index only earns its keep past
// 50,000 URLs or 50MB; with ~20 pages it just added a layer of indirection that
// Search Console reports on separately and that has to be kept in sync.
//
// Required env vars:
//   SUPABASE_URL       — same value as VITE_SUPABASE_URL
//   SUPABASE_ANON_KEY  — same value as VITE_SUPABASE_ANON_KEY
//
// Runs from `npm run build` BEFORE `vite build`, so that Vite's copy of
// public/ -> dist/ picks these files up. Generating them afterwards writes into
// a directory that has already been copied, and nothing ships.

import { createClient } from '@supabase/supabase-js'
import { writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const SITE_URL = 'https://hockeyshotchallenge.com'

// Static pages of the site.
//
// Every entry here MUST resolve to a real route (see src/App.jsx) or a real
// file in public/. App.jsx ends with a catch-all that redirects unknown paths
// to '/', so a stale entry doesn't 404 — it silently becomes a duplicate of the
// homepage, which is worse: Google logs it as a soft-404 / duplicate and it
// drags on crawl trust. Two such entries (/how-many-shots-per-day and
// /10000-shots-app-alternative) were listed here without ever being built.
//
// Keep in sync with the PAGES array in scripts/prerender.js.
const STATIC_PAGES = [
  { loc: '/',                              priority: '1.0', changefreq: 'weekly'  },
  { loc: '/challenges',                    priority: '0.9', changefreq: 'monthly' },
  { loc: '/for-clubs',                     priority: '0.9', changefreq: 'monthly' },
  { loc: '/player',                        priority: '0.8', changefreq: 'monthly' },
  { loc: '/1000-shot-rookie-challenge',            priority: '0.8', changefreq: 'monthly' },
  { loc: '/2500-shot-pro-challenge',               priority: '0.8', changefreq: 'monthly' },
  { loc: '/5000-shot-elite-challenge',             priority: '0.8', changefreq: 'monthly' },
  { loc: '/10000-shot-hall-of-famer-challenge',    priority: '0.8', changefreq: 'monthly' },
  { loc: '/coach',                         priority: '0.7', changefreq: 'monthly' },
  { loc: '/association-partnership',       priority: '0.7', changefreq: 'monthly' },
  { loc: '/province-wide-challenge',       priority: '0.7', changefreq: 'monthly' },
  { loc: '/blog',                          priority: '0.7', changefreq: 'monthly' },

  // Printable trackers — static files in public/, generated by
  // scripts/gen-trackers.mjs. These target "free printable shot tracker"
  // searches, the top of the paper-first funnel.
  // Listed WITHOUT .html: Cloudflare Pages 308-redirects /x.html -> /x, and a
  // sitemap must list the final URL, not one that redirects.
  { loc: '/1k-tracker',               priority: '0.7', changefreq: 'monthly' },
  { loc: '/2_5k-tracker',             priority: '0.7', changefreq: 'monthly' },
  { loc: '/5k-tracker',               priority: '0.7', changefreq: 'monthly' },
  { loc: '/10k-tracker',              priority: '0.7', changefreq: 'monthly' },

  { loc: '/blog/getting-started',          priority: '0.6', changefreq: 'monthly' },
  { loc: '/blog/how-squad-battles-work',   priority: '0.6', changefreq: 'monthly' },
  { loc: '/blog/off-ice-drills',           priority: '0.6', changefreq: 'monthly' },
  { loc: '/blog/building-practice-routine', priority: '0.6', changefreq: 'monthly' },
  { loc: '/blog/parents-guide-youth-hockey', priority: '0.6', changefreq: 'monthly' },
  { loc: '/blog/rookie-challenge',         priority: '0.6', changefreq: 'monthly' },
  { loc: '/blog/pro-challenge',            priority: '0.6', changefreq: 'monthly' },
  { loc: '/blog/elite-challenge',          priority: '0.6', changefreq: 'monthly' },
  { loc: '/blog/hall-of-famer-challenge',  priority: '0.6', changefreq: 'monthly' },

  // NOTE: /start is deliberately absent. It's a real route but it isn't
  // prerendered, so the SPA fallback serves the homepage's HTML at that URL —
  // Google would read it as a duplicate of '/'. It's a signup form with nothing
  // to rank, and every funnel already links to it directly.
  { loc: '/privacy',                       priority: '0.3', changefreq: 'yearly'  },
]

const __filename = fileURLToPath(import.meta.url)
const __dirname  = dirname(__filename)
const PUBLIC_DIR = join(__dirname, '..', 'public')

function escapeXml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function buildUrlEntry({ loc, lastmod, changefreq, priority }) {
  const parts = [
    `  <url>`,
    `    <loc>${escapeXml(loc)}</loc>`,
  ]
  if (lastmod)    parts.push(`    <lastmod>${escapeXml(lastmod)}</lastmod>`)
  if (changefreq) parts.push(`    <changefreq>${escapeXml(changefreq)}</changefreq>`)
  if (priority)   parts.push(`    <priority>${escapeXml(priority)}</priority>`)
  parts.push(`  </url>`)
  return parts.join('\n')
}

async function fetchAllClubs(supabase) {
  // Supabase's default row cap is 1000. We paginate to get all 3,002+ clubs.
  const PAGE_SIZE = 1000
  let allClubs = []
  let from = 0

  while (true) {
    const { data, error } = await supabase
      .from('clubs')
      .select('slug, created_at')
      .order('created_at', { ascending: true })
      .range(from, from + PAGE_SIZE - 1)

    if (error) {
      console.error('❌ Supabase query failed:', error.message)
      throw error
    }

    if (!data || data.length === 0) break
    allClubs = allClubs.concat(data)
    if (data.length < PAGE_SIZE) break
    from += PAGE_SIZE
  }

  return allClubs
}

async function main() {
  console.log('📋 Generating club sitemap…')

  const url = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL
  const key = process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY

  // The static sitemap needs no database access, and the club sitemap is
  // intentionally empty while club pages are noindex. So missing credentials
  // must NOT fail the build — that would take the whole deploy down (and with
  // it the static sitemap) over data we aren't publishing yet.
  let clubs = []
  if (!url || !key) {
    console.warn('⚠️  No Supabase env vars — skipping club lookup.')
    console.warn('   Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to include clubs later.')
  } else {
    try {
      const supabase = createClient(url, key, { auth: { persistSession: false } })
      clubs = await fetchAllClubs(supabase)
      console.log(`✅ Fetched ${clubs.length} clubs from Supabase`)
    } catch (e) {
      console.warn(`⚠️  Club lookup failed (${e.message}) — continuing with static pages only.`)
    }
  }

  const today = new Date().toISOString().slice(0, 10)

  // Cloudflare Pages 308-redirects a directory route to its trailing-slash form
  // (/challenges -> /challenges/). Sitemaps must list the final URL. The
  // trackers are real .html files served extensionless, so they take no slash.
  const withSlash = (loc) =>
    loc === '/' || loc.endsWith('-tracker') ? loc : `${loc}/`

  const urls = STATIC_PAGES.map((p) => buildUrlEntry({
    loc: `${SITE_URL}${withSlash(p.loc)}`,
    lastmod: today,
    changefreq: p.changefreq,
    priority: p.priority,
  }))

  // Club pages are noindex until they have real activity (see
  // functions/clubs/[slug].js), so they are deliberately NOT listed — pointing
  // Google at thousands of empty template pages burns crawl budget and invites
  // duplicate-content penalties. When clubs gain traction, push the active ones
  // into `urls` here. A single sitemap holds 50,000 URLs, comfortably more than
  // the ~3,000 clubs, so this stays one file.

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>
`

  mkdirSync(PUBLIC_DIR, { recursive: true })
  writeFileSync(join(PUBLIC_DIR, 'sitemap.xml'), sitemap)

  // Remove the old split files so they stop being served (they'd go stale and
  // Search Console would keep reporting on URLs we no longer publish).
  for (const stale of ['sitemap-static.xml', 'sitemap-clubs.xml']) {
    const f = join(PUBLIC_DIR, stale)
    if (existsSync(f)) { rmSync(f); console.log(`🧹 Removed stale ${stale}`) }
  }

  console.log(`✅ Wrote sitemap.xml (${urls.length} URLs; ${clubs.length} clubs held back as noindex)`)
  console.log('📋 Sitemap generation complete')
}

main().catch((err) => {
  console.error('❌ Sitemap generation failed:', err)
  process.exit(1)
})
